# Generated by Django 5.2.1 on 2025-06-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_source_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['episode__season__number', 'episode__number', 'id']},
        ),
    ]
