# Generated by Django 5.2.1 on 2025-06-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_source_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['episode__season__show__id', 'episode__season__number', 'episode__number', 'id']},
        ),
    ]
