# Generated by Django 5.2.1 on 2025-06-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_source_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={},
        ),
    ]
